# Report about apps in our phone based on questionnaire

Power BI report:
https://app.powerbi.com/view?r=eyJrIjoiNWU3OGYxZGMtODdiMi00NDZjLWIwZjAtMDhiOTQ0NTY5NzEyIiwidCI6IjQ3OTNhOTZhLTA2N2EtNDJhOC05OWRkLWU3YTdiNDk2NDAzOCIsImMiOjl9&pageName=ReportSectionf8df6f40a05b6884ce78
